nelmio_api_doc:
    models: { use_jms: true }
    documentation:
        info:
            title: Cleaning CRM
            description: Cleaning CRM api docs!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/rest(?!/doc$) # Accepts routes under /api except /api/doc
