todo:
    resource: '@TodoBundle/Controller'
    prefix: /rest
    type: annotation
    defaults: { _format: json }

cleaning:
    resource: '@CleaningBundle/Controller'
    prefix: /rest
    type: annotation
    defaults: { _format: json }
