CleaningCRM\Cleaning\Application\Todo\Dto\TodoDto:
  exclusion_policy: ALL

  properties:
    title:
      type: string

    description:
      type: string

    completed:
      type: bool

    start:
      type: string

    end:
      type: string
