parameters:
  todo.bundle_dir: '%kernel.project_dir%/src/Todo'
  common.bundle_dir: '%kernel.project_dir%/src/Common'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  CleaningCRM\Todo\Bridge\Symfony\Bundle\Command\:
    resource: '%todo.bundle_dir%/Bridge/Symfony/Bundle/Command'
    tags: ['console.command']

  CleaningCRM\Todo\Application\Command\Todo\Handler\:
    resource: '%todo.bundle_dir%/Application/Command/Todo/Handler'
    tags: ['messenger.message_handler']

  CleaningCRM\Todo\Application\Query\Todo\Handler\:
    resource: '%todo.bundle_dir%/Application/Query/Todo/Handler'
    tags: ['messenger.message_handler']

  CleaningCRM\Todo\Bridge\Symfony\Bundle\Controller\:
    resource: '%todo.bundle_dir%/Bridge/Symfony/Bundle/Controller'
    tags: ['controller.service_arguments']

  CleaningCRM\Todo\Infrastructure\Persistence\TodoRepository: ~
  CleaningCRM\Todo\Domain\Todo\TodoRepository: '@CleaningCRM\Todo\Infrastructure\Persistence\TodoRepository'

  CleaningCRM\Todo\Infrastructure\Persistence\TodoQueryRepository: ~
  CleaningCRM\Todo\Domain\Todo\TodoQueryRepository: '@CleaningCRM\Todo\Infrastructure\Persistence\TodoQueryRepository'

  CleaningCRM\Todo\Infrastructure\Persistence\SQLEventStore: ~
  CleaningCRM\Common\Domain\EventStore: '@CleaningCRM\Todo\Infrastructure\Persistence\SQLEventStore'

  CleaningCRM\Todo\Infrastructure\Projection\TodoProjection: ~
  CleaningCRM\Todo\Domain\Todo\TodoProjection: '@CleaningCRM\Todo\Infrastructure\Projection\TodoProjection'

  CleaningCRM\Common\Infrastructure\Serializer\SerializerFactory:
    arguments:
      - '%kernel.project_dir%/var/cache/serializer'
      - '%kernel.debug%'
      - '%common.bundle_dir%/Infrastructure/Serializer/Mapping'

  JMS\Serializer\Serializer:
    factory: 'CleaningCRM\Common\Infrastructure\Serializer\SerializerFactory:create'

  JMS\Serializer\SerializerInterface: '@JMS\Serializer\Serializer'

  CleaningCRM\Todo\Infrastructure\Persistence\TodoReadModelMapper: ~

  CleaningCRM\Todo\Bridge\Symfony\Bundle\Converter\DeserializeSubscriber:
    class: CleaningCRM\Todo\Bridge\Symfony\Bundle\Converter\DeserializeSubscriber
    tags: ['kernel.event_subscriber']
