services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  CleaningCRM\Todo\Bridge\Symfony\Bundle\Command\CreateUserCommand:
    tags: ['console.command']
