CleaningCRM\Todo\Domain\Todo\TodoCompletedWasChanged:
    exclusion_policy: ALL

    properties:
        todoId:
            type: CleaningCRM\Todo\Domain\Todo\TodoId
            serialized_name: todo_id

        completed:
            type: bool

        updatedAt:
            type: DateTimeImmutable
            serialized_name: updated_at
