CleaningCRM\Todo\Domain\Todo\TodoDeletedAtWasChanged:
    exclusion_policy: ALL

    properties:
        todoId:
            type: CleaningCRM\Todo\Domain\Todo\TodoId
            serialized_name: todo_id

        deletedAt:
            type: DateTimeImmutable
            serialized_name: deleted_at
