CleaningCRM\Todo\Application\Dto\TodoDto:
  exclusion_policy: ALL

  properties:
    title:
      type: string

    description:
      type: string

    completed:
      type: bool

    interval:
      type: CleaningCRM\Common\Domain\Interval
