CleaningCRM\Cleaning\Application\Client\Dto\AddressDto:
  exclusion_policy: ALL

  properties:
    city:
      type: string

    country:
      type: string

    street:
      type: string

    postcode:
      type: string
