CleaningCRM\Cleaning\Domain\Client\Contact:
  exclusion_policy: ALL

  properties:
    contactId:
      type: CleaningCRM\Cleaning\Domain\Client\ContactId

    personId:
      type: CleaningCRM\Cleaning\Domain\Person\PersonId

    type:
      type: string
