CleaningCRM\Cleaning\Domain\Client\Event\CompanyNameWasChanged:
  exclusion_policy: ALL

  properties:
    clientId:
      type: CleaningCRM\Cleaning\Domain\Client\Event\RegNumberWasChanged

    companyName:
      type: string
