CleaningCRM\Cleaning\Domain\Client\Event\VatNumberWasChanged:
  exclusion_policy: ALL

  properties:
    clientId:
      type: CleaningCRM\Cleaning\Domain\Client\ClientId

    vatNumber:
      type: string
